# Generated by Django 5.2.17 on 2026-10-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('RE_INSPECTION_SCHEDULED', 'Re-inspection scheduled')], default='SCHEDULED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='stores.store')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'RE_INSPECTION_SCHEDULED'])), name='inspection_status_valid')],
            },
        ),
    ]
