# Generated by Django 5.2.17 on 2026-10-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', 'code'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NOT_APPLICABLE', 'Not applicable')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='results/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inspections.checklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspections.inspection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('inspection', 'checklist_item'), name='one_result_per_item_per_inspection'), models.CheckConstraint(condition=models.Q(('outcome__in', ['PASS', 'FAIL', 'NOT_APPLICABLE'])), name='result_outcome_valid')],
            },
        ),
    ]
